# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
build:
docker:
- image: circleci/python:3.6.4
steps:
- checkout
- run: sudo pip install jupyter_client
- run: sudo pip install nbconvert
- run: sudo pip install numpy
- run: sudo pip install matplotlib
- run: sudo pip install sklearn
- run: sudo python3 -m pip install ipykernel
- run: sudo python3 -m ipykernel install --user
- run: jupyter-nbconvert --execute ./.ipynb
- store_artifacts:
path: ./raktika_dz_1.html
destination: raktika_dz_1.ipynb.html